# https://docs.github.com/cn/actions/reference/workflow-syntax-for-github-actions
name: release-build

on:
  push:
    tags:
      - v*.*.*
  pull_request:
      branches:
        - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: |
          npm install
          npm run electron:publish
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
